### ISSUE TITLE
How to generate base64-encoded keystore?

### ISSUE THREAD

**Issue by SergioAlonsoJr** [kobaltcore/renconstruct#13]
Hi, what does a base64-encoded keystore should look like?

Should it look like a very long string?

And how should I paste this string into the config file?

Text from description:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/4298411/170834143-c90da835-c84c-4e02-9ab7-8153cf368ee1.png">

**Comment by kobaltcore** [comment]
Yes, you can indeed just encode it and paste the resulting string into the config file. You will likely have to add quotes to make sure it's properly parsed by the YAML parser though.

You can encode the file with a tool like this: https://www.base64encode.org

**Comment by SergioAlonsoJr** [comment]
I used the website you suggested, and it generated a 2700+ chars string.
But it doesn't start with "<" and doesn't end with ">". Should I manually add those to the string?

Like in the sample file:

<img width="195" alt="image" src="https://user-images.githubusercontent.com/4298411/170871199-4a9d3a94-ad27-484d-b379-b21159c7f648.png">

**Comment by kobaltcore** [comment]
No, those two characters are not required. I only used them to denote placeholders in the example.
Base 64 encoding can generate quite long strings, which is natural because you're encoding the entire binary spectrum into a set of ASCII characters, which naturally will expand the size a bit.

**Comment by SergioAlonsoJr** [comment]
@kobaltcore, it worked perfectly. 

I asked a few people to install the APK generated with keystore overwrite, and they could update it smoothly from the previous version. (outside the Play Store)
