### ISSUE TITLE
Support log line grouping per build type

### ISSUE THREAD

**Issue by devorbitus** [kobaltcore/renconstruct#3]
Creating this issue for reference as a low-hanging-fruit new feature specifically for GitHub Actions would be really nice while not affecting regular installations

Reference: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#grouping-log-lines

```sh
echo "::group::My title"
echo "Inside group"
echo "::endgroup::"
```

![](https://docs.github.com/assets/images/actions-log-group.png)

**Comment by kobaltcore** [comment]
Just to make sure I understand this correctly: This would affect the logging system of renconstruct such that it changes its format to the one you exemplified above, correct?
In cases where renconstruct would run in a GitHub action, it would produce output as normal but would supply "grouping text" at specific points?

**Comment by devorbitus** [comment]
Yes, it could literally be just "around" the different builds as additional logging statements specifically for GH actions. Everything else would be the same.

**Comment by kobaltcore** [comment]
It appears we can check whether we're running in the Actions environment using the `GITHUB_ACTIONS` [environment variable](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables), which will always exist and be set to true if this is the case.

As such, I can add a check to renconstruct and if it is running as an action, it can output action boundaries where appropriate.

**Comment by kobaltcore** [comment]
I have added basic support for this.

One problem is that building platforms aside from Android happens in one shot. That is, there is currently no way to split/group output into several distinct groups.

As such, there will only be these groups:
- Pre-Build Tasks
- Android Build
- Other Builds
- Post-Build Tasks

**Comment by devorbitus** [comment]
Still useful I bet, thanks for this!

**Comment by devorbitus** [comment]
a8fea725770f29ef226aa4b4882aac1a3b8e0204 makes this issue closed, thanks!
